#+TITLE: Bernardo Ameneyro Rodriguez

* Contact
+ *Email:* bameneyr@tennessee.edu
+ *Office:* Ayres 125, 1403 Circle Drive, Knoxville, TN 37996

* Interests
My current research interests encompass the applications of artificial intelligence, data science, machine learning and quantum computing to biology, ecology and medicine. In the past I have worked with stochastic and ODE models for infectious diseases. My personal interests include the development of free and open source software as well as scientific outreach.

* Education
+ PhD (In progress), Department of Mathematics, University of Tennessee at Knoxville, TN, US.
+ MSc (2022), Department of Mathematics, University of Tennessee at Knoxville, TN, US.
+ BSc (2019), Facultad de Ciencias, Universidad de Colima, Col, MX.

* Work Experience
** Research
+ Graduate Research Assistant at Maroulas Research Group (Spring 2021 to present)
  - Quantum framework for topological data analysis of signals
  - Collaborators: Dr Vasileios Maroulas, and Dr George Siopsis
  - Department of Mathematics, University of Tennessee at Knoxville, TN
+ Mathematical and Theoretical Biology Institute (MTBI) (Summer 2019)
  - The role of preferential mating and Wolbachia infection on the /Aedes Aegypti/ population dynamics
  - Collaborators: Dr Anuj Mubayi, Dr Karen Rios-Soto, Dr Marisabel Rodriguez Mesan, Dr Anarina Murillo, Fan Yu, Brian Chau, Zhen Wang, Maximiliano Ponce Chavez, Ulises Jaime-Yepez
  - Arizona State University, AZ
+ Undergraduate Thesis (Fall 2017 to Spring 2019)
  - Effect of timing of initiation of treatment in the dynamics of resistance to antiviral therapy on infections with HIV
  - Adviser: Dr Roberto Saenz
  - Facultad de Ciencias, Universidad de Colima, Col, MX
** Teaching
+ Graduate Teaching Assistant (Secondary Instructor), Department of Mathematics, University of Tennessee at Knoxville, TN
  - Math 123, Finite Mathematics, Fall 2020
  - Math 119, College Algebra, Fall 2019 and Spring 2020
+ Undergraduate Teaching Assistant, Facultad de Ciencias, Universidad de Colima, Col, MX
  - Workshop on Introduction to Statistics with R, July 2018
  - Geometry and Topology, Spring 2018
  - Introduction to Analysis, Fall 2017
  - Discrete Mathematics, Spring 2017
  - Calculus I, Fall 2016
  - Geometry, Fall 2016

* Publications
+ B. Ameneyro, V. Maroulas, and G. Siopsis. Quantum Persistent Homology, arXiv:2202.12965

* Talks
+ Short Talks
  - Quantum Persistent Homology, Southeast Quantum Computing Workshop, Center for Simulational Physics, University of Georgia, Athens, GA, 20th of May 2022 (online synchronous)
  - Quantum Persistent Homology, APS March Meeting, Chicago, IL, 14th to 18th of March 2022 (online video recording)
  - The role of preferential mating and Wolbachia infection on the /Aedes Aegypti/ population dynamics, 11th Annual Undergraduate Research Conference at the Interface of Biology and Mathematics, Knoxville, TN, 17th of November 2019
  - The role of preferential mating and Wolbachia infection on the /Aedes Aegypti/ population dynamics, Mathematical and Theoretical Biology Institute (MTBI), Arizona State University, Tempe, AZ, 25th of July 2019
+ Poster Presentations
  - The role of preferential mating and Wolbachia infection on the /Aedes Aegypti/ population dynamics, Mathematical and Theoretical Biology Institute (MTBI), Arizona State University, Tempe, AZ, 25th of July 2019
  - Effect of the initial concentration of substrate in a process of fermentation by /Zymomonas Mobilis/, XIV Encuentro Nacional de Biologia Matematica, CIMAT, Guanajuato, 10th of October 2018

* Professional Affiliations
+ Member, SACNAS UTK student chapter.

* Skills
** Programming
+ Python, Matlab, Mathematica, R, Julia, LaTeX (Scientific)
+ HTML, CSS, Javascript (Web development)
+ Haskell, Emacs lisp, Bash script, Fish script (Linux ricing)
** Languages
+ Spanish (native)
+ English (fluent)
+ French, Portuguese (basic)
** Others
+ Basic video/audio editing and recording
+ Karate, Kung Fu
+ Soccer, Basketball, Volleyball
+ Cooking, Baking
